Брозовский Максим
kontur-courses/shpora-testing pull request #12
Opened 2024-11-04 04:55 UTC by BMV989

2024-11-04 15:50 UTC, HELLoWorlD01100 requested changes
У нас все тесты(кроме тестов на конструктор) можно разделить на два вида благодаря тому, что у нас возвращается bool: 
- С валидным значением
- С невалидным значением

Мб так и поступим, вместо дублирования?

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +        // В AreEqual нет Assert, значит при падении теста не будет информации о том как упал тест (причина падения)
Рассмотри еще кейс, когда у царя поле parent будет указывать на уже встречающегося царя в родословной. Нам же ничего не мешает так сделать :)

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_ThrowsArgumentException_WhenPrecisionIsNegative()
Проверяется единственный набор аргументов.

Тесты тебе нужны, чтобы при изменении кода отловить какое-то нарушение поведение. Хочется, чтобы тест отражал все варианты.

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_ThrowsArgumentException_WhenScaleLessThanZero()
То же самое, что выше

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_ThrowsArgumentException_WhenScaleLessThanZero()
Нет проверки на пограничные кейсы

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_ThrowsArgumentException_WhenScaleGreaterOrEqualThanPrecision()
Один тест содержит сразу два теста. Давай разделим

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_DoesNotThrow_WhenPrecisionIsPositive()
Не проверяется пограничных кейсов

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_DoesNotThrow_WhenScaleLessThanPrecision()
А если работает все только когда разница между ними 1?

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeTrue_WhenValueIsInteger(string value, int precision, bool onlyPositive) =>
А если Int переполнен?

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeTrue_WhenValueIsInteger(string value, int precision, bool onlyPositive) =>
А если scale тоже позадавать?

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeFalse_WhenValueIsInteger(string value, int precision, bool onlyPositive) =>
Условие(WhenValueInInteger) должно отражать почему тест работает. 
Если я открою тесты и посмотрю почему они упали, я увижу такую картину:
- IsValidNumber_ShouldBeTrue_WhenValueIsInteger
- IsValidNumber_ShouldBeFalse_WhenValueIsInteger

Условие одно, результаты разные. Придется лезть явно в код и читать почему тесты падают, из описания я мало что пойму

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeTrue_WhenValueIsInteger(string value, int precision, bool onlyPositive) =>
А если с нуля начинается?
В общем еще много тестов можно написать :)

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeTrue_WhenValueIsFloatNumber(string value, int precision, int scale,
А еще запятую можно ставить вместо точки

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeTrue_WhenValueIsInteger(string value, int precision, bool onlyPositive) =>
Арабские цифры мы проверили, а другие будем проверять?

2024-11-04 15:50 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeTrue_WhenValueHasSign(string value) => TestShouldBeTrue(value);
А мы же отрицательные проверили в кейсаъ IsValidNumber_ShouldBeTrue_WhenValueIsInteger

2024-11-05 06:27 UTC, BMV989 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +        // В AreEqual нет Assert, значит при падении теста не будет информации о том как упал тест (причина падения)
Случай несколько вырожден, но формально возможен. 
В таком случае возникнет бесконечная рекурсия. 
Рассмотрим простой случай: есть actualTsar и пусть actualTsar.Parent.Parent = actualTsar.
Тогда при сравнении AreEqual(actualTsar, actualTsar) мы будем сравнивать их Parent, но у них тоже есть Parent, а значит их мы тоже будем сравнивать и т. д.
Таким образом мы получим бесконечную последовать вызовов AreEqual для каждого Parent.

2024-11-05 06:27 UTC, BMV989 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +        // В AreEqual нет Assert, значит при падении теста не будет информации о том как упал тест (причина падения)
+

2024-11-05 06:27 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_ThrowsArgumentException_WhenPrecisionIsNegative()
+

2024-11-05 06:27 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_ThrowsArgumentException_WhenScaleLessThanZero()
+

2024-11-05 06:27 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_ThrowsArgumentException_WhenScaleLessThanZero()
+

2024-11-05 06:27 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_ThrowsArgumentException_WhenScaleGreaterOrEqualThanPrecision()
+

2024-11-05 06:28 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_DoesNotThrow_WhenPrecisionIsPositive()
+

2024-11-05 06:28 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void NumberValidator_DoesNotThrow_WhenScaleLessThanPrecision()
+

2024-11-05 06:28 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeTrue_WhenValueIsInteger(string value, int precision, bool onlyPositive) =>
+

2024-11-05 06:28 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeFalse_WhenValueIsInteger(string value, int precision, bool onlyPositive) =>
+

2024-11-05 06:28 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeTrue_WhenValueIsFloatNumber(string value, int precision, int scale,
+

2024-11-05 06:28 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    public void IsValidNumber_ShouldBeTrue_WhenValueHasSign(string value) => TestShouldBeTrue(value);
+

2024-11-06 01:45 UTC, HELLoWorlD01100 requested changes

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +        // В AreEqual нет Assert, значит при падении теста не будет информации о том как упал тест (причина падения)
А почему вырожден?
Ты не смотри на это как в жизни реально есть, у тебя написан код, который такое допускает. 
И т.к мы не можем менять с тобой сурсы, давай обложимся на уровне тестов хотя бы

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase(2, 2, ScaleErrorMessage, Description = "scale == precision")]
Там прям TestName вроде есть

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +        act.Should().NotThrow();
А нам правда важно тестировать валидные аргументы?
Типа, у тебя дофига тестов, которые это уже предполагают и в случае чего, мы поймем на них.

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("12 , 22", 17, 10, false)]
Давай докинем информации о тесте? Если что-то упадет, то придется аргументы разбирать

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("+3.52", 15, 10, false)]
А чем эти тесты отличаются?

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("-1234567890", 11, 8, false)]
А эти тесты чем отличаются?

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("+1.23", 17, 10, false)]
А для целых чисел почему нет теста со плюсом впереди?)

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("+-15", 3, 2, false)]
А если два одинаковых знака?

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("12 , 22", 17, 10, false)]
Например, кейс [TestCase("-300", 4, 0, false)] из другого тестового метода будет сложно понять по аргументам, придется лезть в реализацию и специфику.

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +                .Excluding(p => p.Parent.Id));
А p.Parent.Parent.Id мы не будем учитывать? :)

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +                .Excluding(p => p.Parent.Id));
Мы в другом треде говорили про бесконечную рекурсию. А тут какое поведение будет?

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("X", 17, 10, false)]
Кроме римских есть еще различные цифры, и числа из них, на удивление, будут валидными :)

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("1\n.5", 3, 2, true)]
А если неэкранируемый на конце? или в начале?

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("-0.00", 3, 2, true)]
Интересный же кейс) Почему положительного кейса нету такого?

2024-11-06 01:45 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("1\n.5", 3, 2, true)]
Лучше похожие кейсы рядом писать, чтобы контекст постоянно не переключать(например,100 и 300)

2024-11-06 05:25 UTC, BMV989 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +        // В AreEqual нет Assert, значит при падении теста не будет информации о том как упал тест (причина падения)
Окей согласен

2024-11-06 06:54 UTC, BMV989 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("-1234567890", 11, 8, false)]
Убрал

2024-11-06 07:07 UTC, BMV989 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +                .Excluding(p => p.Parent.Id));
Да, к сожалению будет(

2024-11-06 07:14 UTC, BMV989 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +                .Excluding(p => p.Parent.Id));
+ Я писал тест исходя из actualTsar и expectedTsar, поэтому я не стал брать рекуретное обобщение

2024-11-06 16:53 UTC, BMV989 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +                .Excluding(p => p.Parent.Id));
Но так действительно лучше

2024-11-06 16:58 UTC, BMV989 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +                .Excluding(p => p.Parent.Id));
но оно не поможет с рекурсией(

2024-11-06 18:34 UTC, BMV989 commented on Testing/Basic/Homework/1. ObjectComparison/ObjectComparison.cs
> +                .Excluding(p => p.Parent.Id));
оно и не должно, впрочем

2024-11-06 23:56 UTC, HELLoWorlD01100 requested changes

2024-11-06 23:56 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("100\n", 4, 2, true, TestName = "100\n should be valid number")]
Каждый тест кейс - это тестирование какого-то конкретного случая. И этот случай хотелось бы описать словами, т.к сейчас мне придется лезть в код и смотреть почему этот аргумент валидный или наоборот невалидный. 

Сейчас в случаях, где указаны просто аргументы в TestName'е, как будто нет смысла. Я и так смогу посмотреть аргументы, а мне важен что это за случай.

В случае с 100\\n у меня вообще кажется в TestName'е при запуске тестов по итогу будет просто 100?) И как понять что было не так?

Это можно было бы назвать типа: When \\n at the end of a number

2024-11-06 23:56 UTC, HELLoWorlD01100 commented on Testing/Basic/Homework/2. NumberValidator/NumberValidatorTests.cs
> +    [TestCase("-1234567890.1234567890", 20, 10, false, TestName = "-1234567890.1234567890 should be invalid number because precision < 21")]
Тут тоже: мне недостаточно просто знать аргументов, мне важно знать какой сценарий покрывает тест

2025-06-08 08:24 UTC, closed without merging